### ISSUE TITLE
Expose access to React Table Functions(getPrePaginationRowModel(), getRowModel())

### ISSUE THREAD

**Issue by dbnar2** [Kuechlin/mantine-data-grid#100]
Is there a way you could expose access to certain react table functions such as getPrePaginationRowModel(), getRowModel() ?

Maybe in a similar way as material-react-table: https://www.material-react-table.com/docs/examples/data-export#data-export-example

This would be useful because it would allow the ability to be able to create custom actions such as creating a  Data Export component, or other functionality for the table without adding overhead to the actual mantine-data-grid component.

**Comment by dbnar2** [comment]
I do want to emphasize I am not asking for a "renderTopToolbarCustomActions" like in material-react-table just a way to get access to these react-table functions. Maybe with some type of hook?

**Comment by dbnar2** [comment]
Realized that tableRef.current can be used to access table component

**Comment by Kuechlin** [comment]
I have updated the examples and in [External Filters Example](https://kuechlin.github.io/mantine-data-grid/#/example/externalfilter) you can see how to get access to the table instance with the `useDataGrid()` hook.

**Comment by dbnar2** [comment]
This works great also thanks so much!
