### ISSUE TITLE
Mantine inputs not working

### ISSUE THREAD

**Issue by SamuelLin95** [Kuechlin/mantine-data-grid#105]
## Description

Using mantine inputs such as Select, TextInput under cell() will not work

## Expected Behaviour

Inputs such as Select should show the dropdown list

## Additional Information

https://codesandbox.io/s/mantine-data-grid-starter-forked-gr6krh?file=/src/DataGrid.tsx
Removing this line ```{...form.getInputProps(`test`)}``` will make the input work but the data will not be binded to form

**Comment by Kuechlin** [comment]
I have added an [ediable cell example](/mantine-data-grid/#/example/editable)
inspired by [react-table editable data](https://tanstack.com/table/v8/docs/examples/react/editable-data)
