### ISSUE TITLE
Losing Focus on Filter Input

### ISSUE THREAD

**Issue by specOper99** [Kuechlin/mantine-data-grid#106]
## Description

when using the filter functions and entering any value the focus is directly removed from the input field while the character pressed shows in the field successfully 

## Expected Behaviour

the focus must stay inside the input field till a tab is pressed or a mouse click outside the input happens

## Note

this happens in version 0.0.19

**Comment by specOper99** [comment]
The error was **fixed** after updating the Mantine core and other packages related to it to the latest version
thanks to [npm-check](https://www.npmjs.com/package/npm-check)

**Comment by naimulcsx** [comment]
Updating to the latest version of mantine packages doesn't work for me. Tested various combinations

- @mantine/core 5.5.5 + mantine-data-grid 0.0.20
- @mantine/core 5.5.5 + mantine-data-grid 0.0.18
- @mantine/core 5.4.0 + mantine-data-grid 0.0.20
- @mantine/core 5.4.0 + mantine-data-grid 0.0.18

Can you please take a look into this? @Kuechlin
