### ISSUE TITLE
BUG: Date Filter Not Returning Row Upon Truthy Expression

### ISSUE THREAD

**Issue by kentond18** [Kuechlin/mantine-data-grid#107]
Equal dates on row filter do not return matching row even when there is a valid row with matching value.

Investigate further.

[Faulty Function on Equal Dates Within Source Code](https://github.com/Kuechlin/mantine-data-grid/blob/5a59133cc5b0de4fc191d85a56e0d14f0bd9e0db/src/filters/dateFilter.tsx#L74)

Steps To Reproduce:
1. Select Date filter on column with dates
2. Select a valid date within the column and choose Equals for the comparison operator
3. Select Enter

**Comment by Nierhain** [comment]
fixed in v0.0.21
