### ISSUE TITLE
Get selected value from Rows per page selector.

### ISSUE THREAD

**Issue by ID-JA** [Kuechlin/mantine-data-grid#116]
I've build an API endpoint to fetch pagination data 

### Request 
```json
{
   "pageNumber": 1,
   "pageSize": 10
}
```

### Response
```json
{
   "data": [
      {
         "id": "08b6155f-ef25-4550-86d0-a8599271b21e",
         "title": "Ruby Developer",
      },
      {
         "id": "1a80395c-c1a4-4610-9389-1c9e70468de2",
         "title": "Blazor Developer",
      }
   ],
   "currentPage": 1,
   "totalPages": 3,
   "totalCount": 5,
   "pageSize": 2,
   "hasPreviousPage": false,
   "hasNextPage": true
}

```

and I'm asking if this library allows to acquire a selected value from the Select Rows per Page component and utilize it  as `PageSize` value to fetch data?

**Comment by Nierhain** [comment]
We expose an onPageChange callback that returns the selected pageSize and pageIndex whenever they change, so you could use that to fetch your data.
