### ISSUE TITLE
Virtualized

### ISSUE THREAD

**Issue by FernandoNarvaez1904** [Kuechlin/mantine-data-grid#117]
Hello

How can i virtualized rows. I could not find it on the docs :(

**Comment by astahmer** [comment]
made a PR related to that https://github.com/Kuechlin/mantine-data-grid/pull/113
my guess is that this will be built-in soon

**Comment by FernandoNarvaez1904** [comment]
thanks

**Comment by Kuechlin** [comment]
rows are virtualized in version 0.0.22
