### ISSUE TITLE
Async Data: Page size is not set

### ISSUE THREAD

**Issue by Cybermage83** [Kuechlin/mantine-data-grid#120]
## Description

In the example, for asyn data, we can;t set page size to more than first initial value of the array, in that example it is always 10.
But it always takes the first set.

Therefore, it gives incorrect number of pages even though the data is update, due to onPageChange pageSize argument

## Expected Behaviour

When u change the pageSize, we expect to see new pageSize set and # of page to reflect the seleection

When u change the pageSize, we expect to see new pageSize set and # of page to reflect the seleection
## Additional Information

Using latest  0.21

Found on the demo on Async example

**Comment by Kuechlin** [comment]
fixed in version 0.0.22
page size is set when custom pagination state is added
