### ISSUE TITLE
Styles API - td not overriding / adding to style

### ISSUE THREAD

**Issue by Shadowfita** [Kuechlin/mantine-data-grid#125]
## Description

Utilise styles API on datagrid to change TD padding
`
td: {
    padding: "0px",
},`

## Expected Behaviour

Padding on TD elements should be 0 pixels

## Additional Information

`                      <DataGrid
                            fontSize="xs"
                            highlightOnHover
                            styles={{
                                // wrapper: {
                                //     transform: "scale(0.35)",
                                //     transformOrigin: "0 0",
                                // },
                                headerCell: {
                                    width: "100%",
                                },
                                headerCellContent: {
                                    textAlign: "center",
                                    width: "100%",
                                },
                                dataCell: {
                                    width: "100%",
                                },
                                dataCellContent: {
                                    whiteSpace: "unset",
                                    overflow: "unset",
                                    // textAlign: "center"
                                    width: "100%",
                                },
                                td: {
                                    padding: "0px",
                                },
                            }} />`

**Comment by Kuechlin** [comment]
Not all Table styles can be overridden, mantine Table itself has [no styles api](https://github.com/mantinedev/mantine/blob/master/src/mantine-core/src/Table/Table.styles.ts)

for now your only option is to use !important rule.

```typescript
   <DataGrid
      styles={() => ({
        td: {
          padding: '0px !important',
        },
      })}
    />
```
