### ISSUE TITLE
 Selecting single record

### ISSUE THREAD

**Issue by shahns** [Kuechlin/mantine-data-grid#129]
## Description

Currently, the way of selecting records allows for multiple record selection. Is there out-of-the-box way to restrict selection to single record only?

for example, https://ant.design/components/table/

**Comment by naughton** [comment]
`  options={{
  enableMultiRowSelection: false
}}`

However, I've found that this works, but the SelectAll checkbox at the top still selects all...

**Comment by Kuechlin** [comment]
` options={{ enableMultiRowSelection: false }}`

will hide the SelectAll box
