### ISSUE TITLE
Styles are not being applied with dark theme

### ISSUE THREAD

**Issue by DenisBessa** [Kuechlin/mantine-data-grid#130]
## Description
When using dark theme, the colors are not being applied to table contents.

## Additional Information
I've created a git repository to reproduce: **https://github.com/DenisBessa/mantine-data-grid-error-demo**

**Comment by specOper99** [comment]
It has existed since version 0.21.0
Waiting for a solution from then

**Comment by fl0wx** [comment]
im also not able to use it anymore currently caus of the theme issue. are there any plans to fix that @Kuechlin  ?

**Comment by Kuechlin** [comment]
it seems to be a problem with different @mantine/core versions:
- mantine-data-grid uses version 5.6.3 and you are using version 5.9.4
- when the versions are the same the theme is applied, when the versions don't match theme is not applied

**Comment by fl0wx** [comment]
How can this be fixed?IMO It wouldn't be a good idea to be pinned to the meantime version this lib is using

**Comment by fl0wx** [comment]
How can this be solved? Imo it wouldn't be a good idea to be pinned to the same mantine version as this lib

**Comment by Kuechlin** [comment]
the peer dependencies define which version of @mantine/core should be used, other than that i have no idea how to prevent this bug.

**Comment by specOper99** [comment]
> the peer dependencies define which version of @mantine/core should be used, other than that i have no idea how to prevent this bug.

All the versions have the same issue
I am updating the packages since you released 0.0.21 till now and the issue still exists
Currently using the `@mantine/core: "^5.10.0"`

**Comment by naughton** [comment]
I also have this issue.  I upgraded mantine to "^5.10.1", but data-grid has "5.10.0" (no ^).  when you release next, could you change that to add a caret, or at least tilde?  "^5.10.0" or upgrade... this will make it so future minor upgrades of mantine don't cause the split theme context problem.
