### ISSUE TITLE
Theme configuration is not respected

### ISSUE THREAD

**Issue by stasgavrylov** [Kuechlin/mantine-data-grid#134]
## Description

Hello, and first of all – thank you for the great work on the data grid component.

Today I've tried to integrate it in my project, and I've noticed a problem with customization.
I wanted to provide custom loader for `LoadingOverlay` component from `@mantine/core`, which `mantine-data-grid` uses when `loading` flag is true.
Unfortunately, for some reason, the data grid still renders the default loader. 

Am I doing something wrong? I would appreciate any help. It's weird that it's not working as expected, since it seems that `DataGrid` doesn't use its own theme provider. But maybe I'm missing something.

## Expected Behaviour

`DataGrid` should respect the default component props set by the theme provider, especially those that are not set by `DataGrid` itself.

Sandbox – https://codesandbox.io/s/exciting-cloud-jgryuf?file=/src/App.tsx

(I made my own, since the one provided seems broken).

**Comment by Kuechlin** [comment]
Hi,
the providers only work when @mantine/core is the same version as in mantine-data-grid.
mantine-data-grid version 0.1.0 uses @mantine/core version 5.6.3

**Comment by stasgavrylov** [comment]
Thank you!
