### ISSUE TITLE
Demos still use cell rather than render.

### ISSUE THREAD

**Issue by naughton** [Kuechlin/mantine-data-grid#145]
## Description

[The editable example](https://kuechlin.github.io/mantine-data-grid/#/example/editable) still uses cell={} rather than render={}

## Expected Behaviour

Demos should be updated to latest api.

**Comment by Kuechlin** [comment]
can you please provide a link to a react-table example with render={}?
the [react-table example](https://tanstack.com/table/v8/docs/examples/react/editable-data) uses cell={}

**Comment by naughton** [comment]
How embarrassing.   I'm referring to `mantine-datatable`, `DataTableColumn` has a property called `render` and no property called `cell`, but I was googling around and found [this link](https://kuechlin.github.io/mantine-data-grid/#/example/editable) and didn't notice I ended up in a `mantine-datagrid` demo.  Sorry for the false report.
