### ISSUE TITLE
Customize Column Filter component 

### ISSUE THREAD

**Issue by evioleta** [Kuechlin/mantine-data-grid#154]
## Description

Currently there is no way to update the ColumnFilter component. I think it would be great to add the possibility to override it.
check: https://github.com/Kuechlin/mantine-data-grid/blob/main/src/ColumnFilter.tsx 

The other components used can be customized using the **components** prop, check : https://github.com/Kuechlin/mantine-data-grid/blob/main/src/DataGrid.tsx#L98, so I wonder if we can add the possibility to override ColumnFilter component as well.

**Comment by UnsungHero97** [comment]
It would be great to customize the `GlobalFilter` component as well.
