### ISSUE TITLE
Row Styling Based on Data input

### ISSUE THREAD

**Issue by ChinmayGopal931** [Kuechlin/mantine-data-grid#168]
## Description

You currently cannot style rows based on the data being passed. So for instance you cannot make each row a different color based on an array passed as data field. Both Mantine Data and react table already supports this so this is a very needed feature.

## Tasks

Add rowStyling to the props in MantineDataGrid

**Comment by Kuechlin** [comment]
you can style the rows or cells based on the data, 
here is a example witch styles the cells and row on mouse interaction: 
https://kuechlin.github.io/mantine-data-grid/#/example/on-row-click

you can access the data in `onCell` with `cell.row.original` and in `onRow` with `row.original`
