### ISSUE TITLE
pageCount missing

### ISSUE THREAD

**Issue by palamethos** [Kuechlin/mantine-data-grid#19]
Hi, not sure if I'm misunderstanding, but looking at some older commits there was a reference made to pageCount on the paginanation prop: https://github.com/Kuechlin/mantine-data-grid/blob/82ad7d866d50325fbefea336d0da3ffe52b68834/docs/components/Demo.tsx#L99

But then the next commit it reverted to local data again https://github.com/Kuechlin/mantine-data-grid/blob/d3f7833e77338e0f191be1257bc5e0daba8c58fa/docs/components/Demo.tsx#L99-L102

Just checking if it is fully compatible with: https://tanstack.com/table/v8/docs/examples/react/pagination-controlled yet? So that we can fetch external data vs local?

Thank you for the great work so far :)

**Comment by mazipan** [comment]
The example is using local. So it will be a full client side pagination.
In case you need a server-side pagination, I think you can listen the `onPageChange` callback.

But not check it yet with a full use-case.

**Comment by Kuechlin** [comment]
For now the component is only for client data. I will add an example with external Data in the future, but for this it's not only the pagination, the filters and sort order also need to be handled for the external source.


I will have a look at the commits. It's my first open source project where I'm working together with other contributors :)

**Comment by palamethos** [comment]
Perfect, thank you for feedback, looking forward to it supporting it in the future 😊
