### ISSUE TITLE
Adjustable default width

### ISSUE THREAD

**Issue by PointSingularity** [Kuechlin/mantine-data-grid#2]
Thanks for the great library!

I was wondering if there is an option to adjust the initial widths of the elements?

Thanks in advance!

**Comment by Kuechlin** [comment]
Hey, you can set the size of a column in the column options with: 
- minSize
- size
- maxSize

https://tanstack.com/table/v8/docs/api/features/column-sizing#enableresizing

**Comment by PointSingularity** [comment]
> Hey, you can set the size of a column in the column options with:
> 
>     * minSize
> 
>     * size
> 
>     * maxSize
> 
> 
> https://tanstack.com/table/v8/docs/api/features/column-sizing#enableresizing

This solves my problem, thank you!
