### ISSUE TITLE
New features to be added

### ISSUE THREAD

**Issue by moshOntong-IT** [Kuechlin/mantine-data-grid#22]
- [ ] SimpleDataGrid 
- [ ] Inline Editable
- [ ] Checkbox

**Comment by Kuechlin** [comment]
Hey, what do you mean with SimpleDataGrid?

You can use this gird right now in a simple way:
```typescript
<DataGrid
    data={/* data source */}
    columns={[
        { 
            accessorKey: 'text',
            header: 'Text',
        },
        { accessorKey: 'cat' },
        { accessorKey: 'fish' },
        { accessorKey: 'city' },
        { accessorKey: 'value' },
        { 
            accessorKey: 'date',
            cell: (cell) => cell.getValue()?.toLocaleDateString()
        },
    ]}
/>
```

With Checkbox do you mean [row selection](https://tanstack.com/table/v8/docs/guide/row-selection)?

Inline Editable is not in scope of this package, but you can build it link in this example: [react-table inline edit](https://tanstack.com/table/v8/docs/examples/react/editable-data?from=reactTableV7&original=https://react-table-v7.tanstack.com/docs/examples/editable-data)
