### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by mjkuhlen** [Kuechlin/mantine-data-grid#35]
Just trying to get a basic implementation of this data table live on my site, regardless of how I set it up I keep getting the following errors in the console. Code and Errors are below.  I am using Mantine v5.0.0; {data} is a response from my backend and this portion of the component doesn't load until it has loaded.  I've tried replacing the backend data call with a hard coded array but that still failed. ie:

const testdata = [{'studentID':2001,'ticketTitle':'Test'}]
`    
<DataGrid
        data={data}
        columns={[
            {
                accessorKey: "studentID",
                header: "Student ID",
                filterFn: stringFilterFn,
            },
            {
                accessorKey: "ticketTitle",
                header: "Issue",
                filterFn: stringFilterFn
            }
        ]}
        />
`

![InvalidHooks_TypeError](https://user-images.githubusercontent.com/35339014/181363748-c4df3972-eed0-4e82-a7b0-6cf683b9814f.PNG)
![joComponent](https://user-images.githubusercontent.com/35339014/181363749-8a2a029a-ea8a-4420-a61d-6b341e3dfa32.PNG)

**Comment by mazipan** [comment]
Could you reproduce using codesandbox?

**Comment by mjkuhlen** [comment]
So, I updated to React18, made the changes to the DOM and now everything is working.
