### ISSUE TITLE
onClick Issues

### ISSUE THREAD

**Issue by mjkuhlen** [Kuechlin/mantine-data-grid#47]
I have a table that includes a cell with a Button, I'd like to use that button to control the state of a Modal.  When adding onClick to the button, the 'click' is being registered multiple times when the table is being rendered and not at all if the user actually clicks the button. Here is a CodeSandbox with a working example of the issue: 
https://codesandbox.io/s/modest-shape-zhw157?file=/src/App.js

**Comment by mazipan** [comment]
Wrap your onclick function.

```tsx
onClick={() => console.log('clicked'}}
```

**Comment by mjkuhlen** [comment]
Argh.  Why is it the little things! Thanks.
