### ISSUE TITLE
Warning: Prop `style` did not match. Server

### ISSUE THREAD

**Issue by moshOntong-IT** [Kuechlin/mantine-data-grid#59]
I do not know if this project has been support the server side  in Next js framework. If ever do, then can you please help me how to fix this?

`Warning: Prop `style` did not match. Server: "position:relative;--radix-scroll-area-corner-width:0px;--radix-scroll-area-corner-height:0px" Client: "position:relative;--radix-scroll-area-corner-width:0px;--radix-scroll-area-corner-height:0px;height:"`

**Comment by Kuechlin** [comment]
i have never used next js.
have you followed the guide on [how to use mantine with next js](https://mantine.dev/guides/next/)?
