### ISSUE TITLE
Draft: Ability to control table state

### ISSUE THREAD

**Issue by arnaud-cortisse** [Kuechlin/mantine-data-grid#61]
## Description

There are some use cases where you want to control the table state from where it's instantiated. 

For example:
- You browse through your table, change the sorting and the pagination. 
- You click on one of the rows and navigate to another page. 
- You navigate back to the table. Here, you would expect to retrieve the table's previous state (with the sorting and pagination). 

## Implementation Model

- A new optional property `state`.

**Comment by arnaud-cortisse** [comment]
Issues with current implementation, will reopen when I have more time

**Comment by mjkuhlen** [comment]
I'm not sure about saving which page you were on previously, but I've been saving sorting and filtering to localStorage and then loading that via the initialState property to save some of those settings.  

```
const [tableState, setTableState] = useLocalStorage({})

<DataGrid
data={data}
onSort={(sorting) => {const tableSort = sorting; setTableState(prevState => ({...prevState, sorting:tableSort}))}};
onFilter={(filter) => {const tableFilter = filter; setTableState(prevState => ({...prevState, columnFilters:tableFilter}))}};
columns={[columninfo]}
initialState={tableState}
>
```

**Comment by arnaud-cortisse** [comment]
> I'm not sure about saving which page you were on previously, but I've been saving sorting and filtering to localStorage and then loading that via the initialState property to save some of those settings.
> 
> ```
> const [tableState, setTableState] = useLocalStorage({})
> 
> <DataGrid
> data={data}
> onSort={(sorting) => {const tableSort = sorting; setTableState(prevState => ({...prevState, sorting:tableSort}))}};
> onFilter={(filter) => {const tableFilter = filter; setTableState(prevState => ({...prevState, columnFilters:tableFilter}))}};
> columns={[columninfo]}
> initialState={tableState}
> >
> ```
> 
> There's an 'onPageChange' property, I haven't looked at that, but perhaps you can find/save the location in there and also save it to localStorage similarly.

I initially wanted to implement using `initialState`, but it doesn't cut it and here is why:
- You set `initialState.pagination.pageIndex` to 2 (because it was your previous state). 
- You go to page index 3. 
- You change the sorting using the UI. 
- The table's page index is automatically set to index 2 (instead of 0 when you don't use `initialState`). Not good UX IMO :(

**Comment by Kuechlin** [comment]
When you change the sorting or filters in the UI, it will always jump to page 0.
This behavior comes from react-table, and is intentional.

For overriding state behavior, i added a state prop so you can control partial parts of the state.
