### ISSUE TITLE
Adjust heigt to parent box

### ISSUE THREAD

**Issue by fl0wx** [Kuechlin/mantine-data-grid#72]
## Description

I would like to have the datagrid to adjust its heigt based on the parent box is it in and then presents a acrollbar in the table body like here in my mui example: 
![image](https://user-images.githubusercontent.com/2448081/184094127-90b3437a-42df-415f-87fb-de0c08934a0d.png)

Currently, if the box size is smaller than the datagrid size, it just cuts off:
![image](https://user-images.githubusercontent.com/2448081/184094314-45f29af2-ca99-4bef-8765-5351c8fccbf9.png)

**Comment by Kuechlin** [comment]
implemented in #82

use height property to customize table height, with 100% it will fit parent container.
