### ISSUE TITLE
Error with async pagination 

### ISSUE THREAD

**Issue by raulzc3** [Kuechlin/mantine-data-grid#75]
## Description

There is an error with the total number of entries while using async pagination, if I use the prop total={17} (just an example), the DataGrid pagination shows the correct amount of pages (in this case it will show 10 pages with 10 rows each) but in the footer of the table, where it shows the current rows and the total rows, it isn't working properly.

Right now I am working with a dataset of 17 rows, where I only get the 10 I need per page from database, not the full database at the same time (this 17 rows will be thousands in the future). The total rows in the page only shows the length of the current array that I have, not the real amount of rows that I have in my database, even if I use the "total" prop.

You can see this same behaviour in the async demo.

## Expected Behaviour
First page (10 rows per page): 
Showing 1 - 10 of 17 result

Second page (10 rows per page): 
Showing 11 - 17 of 17 result

## Additional Information
Code: 
```
<DataGrid
                data={dataSource.data} // Array with length 10 in first page and 7 in second page
                total={dataSource.total} // 17
                columns={columns}
                striped
                highlightOnHover
                withPagination
                withSorting
                onPageChange={({ pageIndex, pageSize }) => {
                    doCall({ page: pageIndex, limit: pageSize });
                }}
            />
```
Output:
First page:
![image](https://user-images.githubusercontent.com/36905578/185064596-d67e9b41-6533-40aa-82e0-de4b6c176175.png)

Second page: 
![image](https://user-images.githubusercontent.com/36905578/185064727-c37f4f11-e332-4f87-9bde-7364c06eb870.png)

**Comment by Nierhain** [comment]
fixed in v0.0.15
