### ISSUE TITLE
Pagination: Last Number in Dropdown is unclickable

### ISSUE THREAD

**Issue by entem-smp** [Kuechlin/mantine-data-grid#76]
## Description
Last Number (100) in Dropdown is unclickable, eventually ist the Scrollbar overlapping it?
why is there a vertical Scrollbar? 100 is perfactly displayable in the Dropdown size.

It woud be nice, is there was n option to set the default Pagination Size (is always 10, even if you give pageSizes={["20","50","100"]})

**Comment by Kuechlin** [comment]
Can you provide a code example to reproduce the bug? for me the 100 is always clickable.

There is a option to set the default page size with initial state:
```typescript
<DataGrid
  data={[]}
  withPagination
  pageSizes={['20', '40', '60']}
  initialState={{
    pagination: {
      pageSize: 20,
    },
  }}
/>
```

**Comment by Kuechlin** [comment]
No response received
