### ISSUE TITLE
External Filters

### ISSUE THREAD

**Issue by entem-smp** [Kuechlin/mantine-data-grid#77]
## Description
it woud be very nice if the Filters are also avialebal as external components. For including them in a SideBar, or building custom layouts.

eventually use like this:
```
<App>
   <SideBar>
      <Stack>
         <Filter
              name="DateFilter"
              dataGrid: "Table"
              accessorKey: "date"
              filterFn: dateFilterFn
              onChange={(e)=>(updateFilterList(e)}
          />
      </Stack>
   </SideBar>
   <DataGrid
      id = "Table"
      data={data}
      columns={columns}
   />
</App>
```

**Comment by fl0wx** [comment]
@entem-smp this is achievable via table state.
https://kuechlin.github.io/mantine-data-grid/example/state

Snippet:
```
const [columnFilters, setColumnFilters] = useState<ColumnFiltersState>([]);

....
onFilter={setColumnFilters}
state={{
  columnFilters,
}}
.....

```

with that you are able to set the "columnFilters" via external code like an button click or sidebar. 

Example content of columnfilters can be extracted from: https://kuechlin.github.io/mantine-data-grid/example/initial-state
Snippet:
`[{ id: 'value', value: { op: 'gt', value: 100 } }]`

hope that helps
