### ISSUE TITLE
Consider deploy demo web to other host provider

### ISSUE THREAD

**Issue by mazipan** [Kuechlin/mantine-data-grid#86]
## Description

The problem with GitHub Pages is because it's not deployed on the root, so sometimes your page can give 404 if you hard reload.

For example: try to visit https://kuechlin.github.io/mantine-data-grid/example, do the hard reload

## Expected Behaviour

All page is 200 even doing hard reload

## Additional Information

Options:
- Netlify
- Surge
- Vercel

Vercel and Netlify support custom fallback for SPA.
For surge, you need to do custom flow: https://surge.sh/help/adding-a-200-page-for-client-side-routing

**Comment by Kuechlin** [comment]
i think i will keep using GitHub pages, but i will change the router to a hash router.
