### ISSUE TITLE
Locale not working on DataGrid

### ISSUE THREAD

**Issue by Sven-Quantix** [Kuechlin/mantine-data-grid#88]
## Description

I attempted to change some labels to be dutch. So that my clients will be able to read it, but doesn't seem to change in my front-end.

`locale={{
        globalSearch: "Zoeken...",
        pageSize: "Rijen per pagina",
        pagination: (firstRowNum, lastRowNum, maxRows) => (
          <>
            Er zijn <b>{firstRowNum}</b> - <b>{lastRowNum}</b> van de{" "}
            <b>{maxRows}</b> resultaten
          </>
        ),
      }}`

## Expected Behaviour

Table text should change to my configuration

**Comment by Kuechlin** [comment]
feature is in version 0.0.17
